# Generated by Django 2.1.10 on 2019-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=200, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caller', models.CharField(max_length=20)),
                ('audio_message_url', models.TextField(null=True)),
                ('audio_message_duration', models.DurationField(null=True)),
                ('input_sequence', models.TextField(blank=True, default='')),
            ],
        ),
    ]
